### PR TITLE
Adding new sites

### PR DESCRIPTION
**Pull request by mairaw**
Don't merge this yet. Let's coordinate on timing. /cc @bradygaster

### CODE REVIEW

**Comment by BryanLa** [comment]
Thanks @mairaw!

All looks great, except for this part:
- `it is recommended that you open an issue in the associated docs.microsoft.com repository to discuss the nature of your change and get approval. 

We've typically discouraged filing issues, and favored keeping all of the discussion in a PR. I believe @tysonn actually turned them off on the ACOM repo as they got hard to manage, and created more overhead (vs. getting the actual suggested/proposed content via PR). I know you're looking at it more as a discussion mechanism, but I think it would be useful to talk about this w/Tyson before going ahead.

Everything else looks great though and I'd be happy to merge it once we discuss.

**Comment by mairaw** [comment]
Thanks @BryanLa! Sure, let's discuss this. If needed, I can remove that part for the release until we have time to reach a consensus. The intention here is that an external contributor would not waste their time working on something that wouldn't be approved in the end. That's the same process that the PUs are also using: https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing.md

Ideally, we'd have the same processes across the org, but if needed, we'll have to keep some guidelines specific to our product. I'd love to hear how the experience was in ACOM world. Didn't people get frustrated if they wrote an entire new topic that simply gets rejected?

**Comment by BryanLa** [comment]
Sounds good, @mairaw. 

Actually, in the 1+ year I've been doing pull request review/approval for our pillar, I've only seen one person submit an entirely new article via the public contribution process, and it was a MSFT field employee. The place I've seen the GitHub "Issues" feature used the most though, is in code samples repos, and it's typically support-like in nature (ie: I can't get the sample to work, please help!). Typically the public submissions tend to be slight improvements in text, or fixes to typo/grammar errors.

If you want to remove that part, I'll go ahead and merge everything else when you and @bradygaster are ready?

**Comment by mairaw** [comment]
@BryanLa made the change. I'll let you know next week when we're ready to merge.

**Comment by BryanLa** [comment]
Sounds good, thanks again @mairaw !

**Comment by mairaw** [comment]
@BryanLa this is ready to go. Please merge this!

**Comment by BryanLa** [comment]
Done!

**Pull request merged**
