### PR TITLE
External

### PR DESCRIPTION
**Pull request by msmbaldwin**

### CODE REVIEW

**Comment by msmbaldwin** [comment]
@PatAltimore please review

**Comment by BryanLa** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[ContributorGuide/template.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/template.md) | :warning:Warning | | [Details](#user-content-ContributorGuide/template.md)
[ContributorGuide/contributing-and-publishing.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/contributing-and-publishing.md) | :white_check_mark:Succeeded | | [Details](#user-content-ContributorGuide/contributing-and-publishing.md)
[ContributorGuide/create-new-article.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/create-new-article.md) | :white_check_mark:Succeeded | | [Details](#user-content-ContributorGuide/create-new-article.md)
[ContributorGuide/git-github-workflow-tutorial.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/git-github-workflow-tutorial.md) | :white_check_mark:Succeeded | | [Details](#user-content-ContributorGuide/git-github-workflow-tutorial.md)
[ContributorGuide/media/azure.png](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/media/azure.png) | :white_check_mark:Succeeded | | [Details](#user-content-ContributorGuide/media/azure.png)

<a name="ContributorGuide/template.md"></a>
### [ContributorGuide/template.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/template.md)
 - **Line Unspecified**: **[Warning]** unexpected type Array for metadata title, the expected type is string





For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C22%5C3f15c7f7-33a2-c227-9762-e8ed18b2e972%5CPullRequest%5C201611212359488195-40%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PatAltimore** [comment]
@msmbaldwin I think you have an old version of contributing-and-publishing.md.  Could you sync & update the PR?

**Comment by BryanLa** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[ContributorGuide/create-new-article.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/create-new-article.md) | :warning:Warning | | [Details](#user-content-ContributorGuide/create-new-article.md)
[ContributorGuide/template.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/template.md) | :warning:Warning | | [Details](#user-content-ContributorGuide/template.md)
[ContributorGuide/contributing-and-publishing.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/contributing-and-publishing.md) | :white_check_mark:Succeeded | |
[ContributorGuide/git-github-workflow-tutorial.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/git-github-workflow-tutorial.md) | :white_check_mark:Succeeded | |
[ContributorGuide/media/azure.png](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/media/azure.png) | :white_check_mark:Succeeded | |

<a name="ContributorGuide/create-new-article.md"></a>
### [ContributorGuide/create-new-article.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/create-new-article.md)
 - **Line 33**: **[Warning]** Invalid file link:(~/git-and-github-repository-initial-setup).

<a name="ContributorGuide/template.md"></a>
### [ContributorGuide/template.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/template.md)
 - **Line 77**: **[Warning]** Invalid file link:(~/understand-explore/rms-for-individuals-user-signup.md#technical-overview-of-the-sign-up-process).
 - **Line unspecified**: **[Warning]** unexpected type Array for metadata title, the expected type is string

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C23%5C3f15c7f7-33a2-c227-9762-e8ed18b2e972%5CPullRequest%5C201611231822057155-40%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by BryanLa** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[ContributorGuide/create-new-article.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/create-new-article.md) | :warning:Warning | | [Details](#user-content-ContributorGuide/create-new-article.md)
[ContributorGuide/template.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/template.md) | :warning:Warning | | [Details](#user-content-ContributorGuide/template.md)
[ContributorGuide/contributing-and-publishing.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/contributing-and-publishing.md) | :white_check_mark:Succeeded | |
[ContributorGuide/git-github-workflow-tutorial.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/git-github-workflow-tutorial.md) | :white_check_mark:Succeeded | |
[ContributorGuide/media/azure.png](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/media/azure.png) | :white_check_mark:Succeeded | |

<a name="ContributorGuide/create-new-article.md"></a>
### [ContributorGuide/create-new-article.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/create-new-article.md)
 - **Line 33**: **[Warning]** Invalid file link:(~/git-and-github-repository-initial-setup).

<a name="ContributorGuide/template.md"></a>
### [ContributorGuide/template.md](https://github.com/Microsoft/Docs/blob/external/ContributorGuide/template.md)
 - **Line 77**: **[Warning]** Invalid file link:(~/understand-explore/rms-for-individuals-user-signup.md#technical-overview-of-the-sign-up-process).
 - **Line unspecified**: **[Warning]** unexpected type Array for metadata title, the expected type is string

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C23%5C3f15c7f7-33a2-c227-9762-e8ed18b2e972%5CPullRequest%5C201611231840520404-40%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
